name: FoF Filter PHP

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@1.x
    with:
      enable_backend_testing: true
      enable_phpstan: true
      php_versions: '["7.4", "8.0", "8.1"]'

      backend_directory: .
